variable "environment" {
  description = "The name of the environment in which we're deploying"
}

variable "aws_region" {
  default = "eu-west-2"
}

variable "prm-application-source-bucket" {
  default = "dummy_bucket_value"
}

variable "github_token" {
  default = "dummy_token_value"
}

variable "codebuild-cache-bucket-name" {
  description = "Name of the S3 bucket that is supposed to hold cache information for CodeBuild"
}

variable "codebuild-dep-scan-report-bucket-name" {
  description = "Name of the S3 bucket that is supposed to hold the reports generated by the OWASP dependency check"
}

variable "assume_role" {
  description = "whether or not to create user role in pipeline. Either 1 or 0"
}
